"""Medical foundation: five per-dog medical tables.

Revision ID: 0002_medical_foundation
Revises: 0001_baseline
Create Date: 2026-09-22 18:03:31.834874

Adds medical_records, vaccinations, medications, health_observations and
follow_ups, each with a CASCADE foreign key to dogs.id and a SET NULL one to
users.id. Additive only: no existing table, column or row is touched.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002_medical_foundation'
down_revision = '0001_baseline'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_ups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('cancelled', 'completed', 'missed', 'pending')", name='ck_follow_ups_status'),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('follow_ups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_follow_ups_dog_id'), ['dog_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_ups_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_ups_status'), ['status'], unique=False)

    op.create_table('health_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('symptoms', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('temperature_c IS NULL OR (temperature_c >= 30.0 AND temperature_c <= 45.0)', name='ck_health_observations_temperature_c'),
    sa.CheckConstraint('weight_kg IS NULL OR (weight_kg > 0 AND weight_kg <= 120.0)', name='ck_health_observations_weight_kg'),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('health_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_observations_dog_id'), ['dog_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_observations_observation_date'), ['observation_date'], unique=False)

    op.create_table('medical_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('veterinarian', sa.String(length=120), nullable=True),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("record_type IN ('checkup', 'dental', 'diagnostic', 'emergency', 'other', 'surgery', 'treatment')", name='ck_medical_records_record_type'),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_records_dog_id'), ['dog_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_records_visit_date'), ['visit_date'], unique=False)

    op.create_table('medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('medication_name', sa.String(length=120), nullable=False),
    sa.Column('dosage', sa.String(length=80), nullable=False),
    sa.Column('frequency', sa.String(length=80), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('prescribed_by', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('active', 'completed', 'discontinued')", name='ck_medications_status'),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medications_dog_id'), ['dog_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medications_status'), ['status'], unique=False)

    op.create_table('vaccinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('vaccine_name', sa.String(length=120), nullable=False),
    sa.Column('administered_date', sa.Date(), nullable=True),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('veterinarian', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('completed', 'overdue', 'scheduled')", name='ck_vaccinations_status'),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vaccinations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vaccinations_dog_id'), ['dog_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vaccinations_next_due_date'), ['next_due_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # Drops only the five tables added above, and every medical row with them.
    # The baseline tables are untouched. Back the database up before running
    # this anywhere that holds real records.
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaccinations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vaccinations_next_due_date'))
        batch_op.drop_index(batch_op.f('ix_vaccinations_dog_id'))

    op.drop_table('vaccinations')
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medications_status'))
        batch_op.drop_index(batch_op.f('ix_medications_dog_id'))

    op.drop_table('medications')
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_records_visit_date'))
        batch_op.drop_index(batch_op.f('ix_medical_records_dog_id'))

    op.drop_table('medical_records')
    with op.batch_alter_table('health_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_observations_observation_date'))
        batch_op.drop_index(batch_op.f('ix_health_observations_dog_id'))

    op.drop_table('health_observations')
    with op.batch_alter_table('follow_ups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_follow_ups_status'))
        batch_op.drop_index(batch_op.f('ix_follow_ups_due_date'))
        batch_op.drop_index(batch_op.f('ix_follow_ups_dog_id'))

    op.drop_table('follow_ups')
    # ### end Alembic commands ###
