"""Health alerts and the notification outbox.

Revision ID: 0003_health_alerts
Revises: 0002_medical_foundation
Create Date: 2026-09-23 02:57:26.258265

Adds `health_alerts` (findings tracked until resolved) and `notifications`
(the outbox; nothing delivers from it yet). Additive only: no existing table,
column or row is touched.

The partial unique index uq_health_alerts_active_identity is what makes a
repeated sync idempotent — only one non-resolved alert per
(dog_id, finding_code, entity_key). Resolved rows stay behind it as history.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0003_health_alerts'
down_revision = '0002_medical_foundation'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('finding_code', sa.String(length=80), nullable=False),
    sa.Column('entity_key', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('risk_score_at_detection', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('first_detected_at', sa.DateTime(), nullable=False),
    sa.Column('last_detected_at', sa.DateTime(), nullable=False),
    sa.Column('detection_count', sa.Integer(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('auto_resolved', sa.Boolean(), nullable=False),
    sa.Column('reopened_from_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("severity IN ('critical', 'high', 'low', 'moderate')", name='ck_health_alerts_severity'),
    sa.CheckConstraint("status IN ('acknowledged', 'open', 'resolved')", name='ck_health_alerts_status'),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reopened_from_id'], ['health_alerts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('health_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_alerts_dog_id'), ['dog_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_alerts_finding_code'), ['finding_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_alerts_last_detected_at'), ['last_detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_alerts_status'), ['status'], unique=False)
        batch_op.create_index('ix_health_alerts_status_severity', ['status', 'severity'], unique=False)
        batch_op.create_index('uq_health_alerts_active_identity', ['dog_id', 'finding_code', 'entity_key'], unique=True, sqlite_where=sa.text("status != 'resolved'"), postgresql_where=sa.text("status != 'resolved'"))

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=True),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('failed', 'pending', 'sent')", name='ck_notifications_status'),
    sa.ForeignKeyConstraint(['alert_id'], ['health_alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_dog_id'), ['dog_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # Drops only the two tables added above, and the alert history with them.
    # The medical and baseline tables are untouched. Back up before running
    # this anywhere holding real alerts.
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_status'))
        batch_op.drop_index(batch_op.f('ix_notifications_event_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_dog_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('health_alerts', schema=None) as batch_op:
        batch_op.drop_index('uq_health_alerts_active_identity', sqlite_where=sa.text("status != 'resolved'"), postgresql_where=sa.text("status != 'resolved'"))
        batch_op.drop_index('ix_health_alerts_status_severity')
        batch_op.drop_index(batch_op.f('ix_health_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_health_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_health_alerts_last_detected_at'))
        batch_op.drop_index(batch_op.f('ix_health_alerts_finding_code'))
        batch_op.drop_index(batch_op.f('ix_health_alerts_dog_id'))

    op.drop_table('health_alerts')
    # ### end Alembic commands ###
